models.py
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class Gyro(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    x_value = db.Column(db.Float, nullable=False)
    y_value = db.Column(db.Float, nullable=False)
    z_value = db.Column(db.Float, nullable=False)


class Accelerometer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    x_value = db.Column(db.Float, nullable=False)
    y_value = db.Column(db.Float, nullable=False)
    z_value = db.Column(db.Float, nullable=False)


class Temp(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    temp_value = db.Column(db.Float, nullable=False)
    humi_value = db.Column(db.Float, nullable=False)


class Current(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, nullable=False)
    voltage = db.Column(db.Float, nullable=False)
    current = db.Column(db.Float, nullable=False)
    power = db.Column(db.Float, nullable=False)

__init__.py
from flask import Flask
import os
from models import db
from utils import settings_utils


def create_background_managers(app):
    from background_managers.sensors_manager import SensorManager
    from background_managers.db_manager import DBManager

    sensors_manager = SensorManager()
    sensors_manager.start()

    db_manager = DBManager(app, db, sensors_manager)
    db_manager.start()

    app.db_manager = db_manager
    app.sensors_manager = sensors_manager


def create_app():
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object("app_config.AppConfig")
    app.secret_key = os.urandom(25)

    db.init_app(app)

    settings_utils.init_settings()

    with app.app_context():
        db.create_all()

        create_background_managers(app)

        from routes import content, errors, sensors_api, settings

        app.register_blueprint(content.content)
        app.register_blueprint(errors.errors)
        app.register_blueprint(sensors_api.sensors)
        app.register_blueprint(settings.settings)

        return app

app.py
from __init__ import create_app


app = create_app()

if __name__ == "__main__":
    APP_PORT = app.config["APP_PORT"]
    APP_HOST = app.config["APP_HOST"]
    DEBUG_MODE = app.config["DEBUG_MODE"]

    app.run(debug=DEBUG_MODE, host=APP_HOST, port=APP_PORT)

routes/content.py
from flask import render_template, Blueprint, current_app
from sensors.sensors_config import SensorsConfig
from utils import graphs_utils, settings_utils
from settings_config import SettingsConfig


content = Blueprint("content", __name__, template_folder='template', static_folder='static')


@content.route("/")
def home():
    sensors_manager = current_app.sensors_manager

    sensors_data = [sensor.parse_sensors_data() for sensor in sensors_manager.get_sensors()]

    return render_template("index.html", sensors_data=sensors_data, sensors_config=SensorsConfig)


@content.route("/settings")
def settings():
    settings_data = settings_utils.load_settings()

    return render_template("settings.html", settings_data=settings_data, settings_config=SettingsConfig)


@content.route("/graphs")
def graphs():
    acceleration_graphs = graphs_utils.generate_acceleration_2d_graphs()
    gyro_graphs = graphs_utils.generate_gyro_2d_graphs()
    temp_graphs = graphs_utils.generate_temp_2d_graphs()
    current_graphs = graphs_utils.generate_current_2d_graphs()

    sensors_graphs = [acceleration_graphs, gyro_graphs, temp_graphs, current_graphs]

    return render_template("graphs.html", sensors_graphs=sensors_graphs)

routes/errors.py
from flask import render_template, Blueprint, redirect, url_for


errors = Blueprint("errors", __name__, template_folder='template', static_folder='static')


@errors.app_errorhandler(404)
def error_404(error):
    return render_template("error.html", message=error)


@errors.app_errorhandler(500)
def error_500(error):
    return render_template("error.html", message=error)


@errors.app_errorhandler(401)
def error_401(error):
    return redirect(url_for("auth.login"))


@errors.app_errorhandler(405)
def error_405(error):
    return render_template("error.html", message=error)

routes/sensors_api.py
from flask import Blueprint, jsonify, current_app
from utils import db_utils
from sensors.sensors_config import SensorsConfig

sensors = Blueprint("sensors", __name__, template_folder='template', static_folder='static')


@sensors.route("/api/sensors/<sensor_name>")
def sensor_data(sensor_name):
    sensors_manager = current_app.sensors_manager

    data = sensors_manager.get_sensor_parsed_data_by_sensor_name(sensor_name)

    return jsonify(data)


@sensors.route("/api/sensors")
def sensors_list():
    sensors_manager = current_app.sensors_manager

    sensors = [sensor.name for sensor in sensors_manager.get_sensors()]

    return jsonify(sensors)


@sensors.route("/api/sensors_data/<sensor_name>")
def sensors_db_data(sensor_name):
    sensor_db_data = []

    if sensor_name == SensorsConfig.ACCELEROMETER_SENSOR_NAME:
        sensor_db_data = db_utils.get_acceleration_data()

    elif sensor_name == SensorsConfig.GYRO_SENSOR_NAME:
        sensor_db_data = db_utils.get_gyro_data()

    elif sensor_name == SensorsConfig.TEMP_SENSOR_NAME:
        sensor_db_data = db_utils.get_temp_data()

    return jsonify(sensor_db_data)

routes/settings.py
from flask import redirect, Blueprint, url_for, request
from utils import settings_utils


settings = Blueprint("settings", __name__, template_folder='template', static_folder='static')


@settings.route("/settings/apply_settings", methods=["POST"])
def apply_settings():
    requests_dict = request.form.to_dict()

    if len(requests_dict.keys()) > 0:
        settings_data = settings_utils.load_settings()

        for settings_mode in requests_dict:
            if settings_mode in settings_data.keys():
                settings_mode_value = requests_dict[settings_mode]

                if settings_mode_value:
                    if settings_mode_value.isnumeric():
                        settings_mode_value = int(settings_mode_value)

                    settings_data[settings_mode] = settings_mode_value

        settings_utils.save_settings(settings_data)

    return redirect(url_for("content.settings"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <script src="{{ url_for('static', filename='main.js') }}"></script>

        <title>MotoSentinel</title>
    </head>
    <body>
        <div class="container">
            <div class="navbar">
                <span class="navbar-home-item">
                    <a href="{{ url_for('content.home') }}">
                        MotoSentinel
                    </a>
                </span>
                <span class="navbar-item">
                    <a href="{{ url_for('content.graphs') }}">
                        Graphs
                    </a>
                </span>
                <span class="navbar-item">
                    <a href="{{ url_for('content.settings') }}">
                        Settings
                    </a>
                </span>
            </div>
            <div class="content">
                {% block content %}
                {% endblock %}
            </div>
            <div class="footer">
                Powered by Flask
            </div>
        </div>
    </body>
</html>

templates/error.html
{% extends "base.html" %}
{% block content %}
    <p>
        Error : {{ message }}
    </p>
{% endblock %}

templates/graphs.html
{% extends "base.html" %}
{% block content %}
        {% for sensor_graphs in sensors_graphs %}
            <div class="graph-container">
                {% if sensor_graphs|length > 0 %}
                    {% for graph in sensor_graphs %}
                        <p>
                            <img class="graph-img" src="{{ graph }}">
                        </p>
                    {% endfor %}

                {% else %}
                    <p>Nothing to show</p>

                {% endif %}
            </div>
        {% endfor %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
        {% for sensor_data in sensors_data %}
            <div class="sensor-container" id="{{ sensor_data[sensors_config.SENSOR_NAME_KEY] }}">
                <script>
                   initSensorUpdate("{{ sensor_data[sensors_config.SENSOR_NAME_KEY] }}");
                </script>

                {% for data in sensor_data %}
                    <p id="{{ data }}">
                        {{ data }} : {{ sensor_data[data] }}
                    </p>
                {% endfor %}
            </div>
        {% endfor %}
{% endblock %}

templates/settings.html
{% extends "base.html" %}
{% block content %}
        {% if settings_config.SETTINGS_PAGE_STRUCT|length > 0 %}
            {% for settings_struct in settings_config.SETTINGS_PAGE_STRUCT %}
                <form class="settings-form" method="POST" action="{{ url_for('settings.apply_settings') }}" enctype="multipart/form-data">
                    <div class="settings-container">
                        <p>
                            {{ settings_struct[settings_config.SETTINGS_PAGE_STRUCT_TITLE_KEY_NAME] }} : ({{ settings_struct[settings_config.SETTINGS_PAGE_STRUCT_TIP_KEY_NAME] }})
                        </p>
                        {% for mode_item in settings_struct[settings_config.SETTINGS_PAGE_STRUCT_MODES_ITEMS] %}
                            <span>
                                <p>
                                    {{  settings_config.SETTINGS_NAMES[mode_item[settings_config.SETTINGS_ITEM_NAME]] }}
                                </p>
                                <input type="{{ mode_item[settings_config.SETTINGS_ITEM_INPUT_TYPE] }}" id="{{ mode_item[settings_config.SETTINGS_ITEM_NAME] }}"
                                        name="{{ mode_item[settings_config.SETTINGS_ITEM_NAME] }}"
                                        value="{{ settings_data[mode_item[settings_config.SETTINGS_ITEM_NAME]] }}">
                            </span>
                        {% endfor %}
                        <button class="settings-button" type="submit">Apply</button>
                    </div>
                </form>
            {% endfor %}
        {% else %}
            <p>
                Nothing to show
            </p>
        {% endif %}
{% endblock %}